### ISSUE TITLE
Not working on GHE

### ISSUE THREAD

**Issue by PAkerstrand** [semantic-release/travis-deploy-once#2]
There seems to be an issue with running `semantic-release` on GitHub Enterprise, and I believe it is due to this package. Whenever I run `semantic_release` in the `after_success` hook I get the following in the log:

```
> semantic-release pre && npm publish && semantic-release post
semantic-release ERR! pre 401 - {
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
```

I believe it is [due to the following in `src.js`](https://github.com/semantic-release/travis-deploy-once/blob/master/src.js#L14-L21):

```js
  const {private: pro} = await request({
    json: true,
    url: `https://api.github.com/repos/${process.env.TRAVIS_REPO_SLUG}`,
    headers: {
      Authorization: `token ${token}`,
      'user-agent': 'travis-deploy-once'
    }
  })
```
There seems to be no reference to the `githubUrl` or the `githubApiPathPrefix`. Has `semantic-release` been verified to work properly on GHE?

_(I have verified that my access-token works properly when I try it with curl locally and use the correct endpoints, such as `${githubUrl}/api/v3/${org}/${repoName}/releases`)_

**Comment by gr2m** [comment]
Hey @PAkerstrand, sorry nobody got back to you yet 😞 I recently [joined the semantic-release maintainers](https://github.com/semantic-release/semantic-release/issues/411) and would be happy to help out. I’m looking into `travis-deploy-once` right now.

As far as I know, `semantic-release` works on GHE. Does this problem still persist for you?

**Comment by davidgeorgeuk** [comment]
Hi @gr2m I'm still experiencing this problem. I suspect this problem is also causing semantic-release/semantic-release#375

**Comment by vanduynslagerp** [comment]
I think we should do something similar to https://github.com/semantic-release/semantic-release/commit/2644badeecc745f40e79778a4b15ed9f9860166a

We should already have the parameters `githubUrl` and  `githubApiPathPrefix` passed to the plugin so it shouldn't be too hard.

We can also use [node-github](https://github.com/mikedeboer/node-github) instead of `axios` as we do for the rest of `semantic-release`. It's really a simple call to know if the repo is private but it might be better to be more consistent.

I'll look in detail ASAP.

@PAkerstrand, @davidgeorgeuk do you know how can I simulate a github pro environment for testing ?

**Comment by davidgeorgeuk** [comment]
@vanduynslagerp Thank you for your help with this! As far as simulating a GHE environment goes, I think the main issue here is that the URL is hard-coded. So if you were to create an alias or proxy on your machine that points to public github, that would probably do the trick.

**Comment by vanduynslagerp** [comment]
We call github only to determine if the repo is private and define if we have to call the Travis pro or the regular Travis API.
We have the necessary options to call GHE in `semantic-release` including in [condition-travis](https://github.com/semantic-release/condition-travis).

I think overall it makes more sense to determine if we have to use Travis pro or regular outside of this module, so it would make it more generic. It's likely that the caller would already know at that point if it's using Travis pro or not, so the current call to github is probably redundant in many cases.

We could move the github call to [condition-travis](https://github.com/semantic-release/condition-travis) and pass the pro/regular option to this package.
Even better we could accept an object in parameter that we would pass directly to [node-travis-ci](https://github.com/pwmckenna/node-travis-ci). This way if there is additional options available there, we wouldn't have to change this package.

It propose something along those lines:
```js
module.exports = (
  {travisOpts, BUILD_LEADER_ID = process.env.BUILD_LEADER_ID} = {}
) => {
// ....
}
```

And the module would be called like this:
```js
travisDeployOnce(); // Travis regular API
travisDeployOnce({travisOpts: {pro: true}}); // Travis pro API
travisDeployOnce({travisOpts: {pro: true}, BUILD_LEADER_ID: 2}); // Travis pro API with BUILD_LEADER_ID
```
/cc @gr2m

**Comment by gr2m** [comment]
> We can also use node-github instead of axios as we do for the rest of semantic-release. It's really a simple call to know if the repo is private but it might be better to be more consistent.

Yes let’s do that

> We could move the github call to condition-travis and pass the pro/regular option to this package.
Even better we could accept an object in parameter that we would pass directly to node-travis-ci. This way if there is additional options available there, we wouldn't have to change this package.

Sounds great! Let’s do it :)
