### ISSUE TITLE
Support installation of node through nvm instead of language key

### ISSUE THREAD

**Issue by felixfbecker** [semantic-release/travis-deploy-once#22]
See https://travis-ci.org/felixfbecker/php-language-server/jobs/291359846#L912-L915

The language is set to `php`, but I install Node 8 with `nvm` in the `after_success` step. You can imagine the same problem if you only run macOS builds that only support `c++` as language.

The current algorithm only works if the language is `node_js`, the determined build leader is always `0` otherwise.

I would propose that if there is no `node_js` build found, but the job number is `1` and the running node version (`process.version`) satisfies `^8.0.0` to elect job `1` as the leader.

**Comment by gr2m** [comment]
I would suggest to use the `BUILD_LEADER_ID` environment variable instead, would that work for you?

**Comment by felixfbecker** [comment]
Yeah that should work. It would be great to mention in the docs that this is required if the language is `node_js` and make the command fail if no language is `node_js` and the variable is not set.

**Comment by gr2m** [comment]
yeah I agree. It's mentioned in the README of this repository: https://github.com/semantic-release/travis-deploy-once

But we should mention it in the main semantic-release docs, too

**Comment by gr2m** [comment]
can you send a PR adding an FAQ entry, maybe after this one? https://github.com/semantic-release/semantic-release#why-does-semantic-release-require-node-version--8

Thanks again Felix!

**Comment by pvdlg** [comment]
I think we should handle this case a bit better and return a better error / log when there is no node job. The currents logs are a bit confusing and don't indicate that there is no node builds.
