### ISSUE TITLE
README example is invalid JavaScript

### ISSUE THREAD

**Issue by eventualbuddha** [semantic-release/travis-deploy-once#36]
This is the example from the README:

```js
const deployOnce = require('travis-deploy-once');

try {
  const result = await deployOnce({travisOpts: {pro: true}, GH_TOKEN: 'xxxxxx', BUILD_LEADER_ID: 1});
} catch (err) {
  // something went wrong, and err will tell you what
}

if (result === true) deployMyThing();
if (result === false) console.log('Some job(s) failed');
if (result === null) console.log('Did not run as the build leader');
```

Since `const` is block scoped, `result` is only available inside the `try` body. Referencing `result` outside that scope results in a `ReferenceError`.

**Comment by pvdlg** [comment]
Yes indeed. Good catch!
Would you want to propose a PR to fix it?

**Comment by eventualbuddha** [comment]
Could either declare it as `let` outside the block (preserves the original intent) or move the remainder of the code into the block and leave the variable as `const` (cleaner, but makes the error potentially come from an unrelated action). What do you think?

**Comment by pvdlg** [comment]
The intent is not to suggest a specific way to handle errors, and `try catch` block but just to demonstrate how to use the library. So both options are ok. The important is for the code to work :)

Maybe declaring `result` as `let` outside the `try catch` is clearer?
