### ISSUE TITLE
Add check for TRAVIS_BUILD_STAGE_NAME

### ISSUE THREAD

**Issue by gr2m** [semantic-release/travis-deploy-once#61]
follow up for https://github.com/semantic-release/semantic-release/issues/390#issuecomment-373913122, https://github.com/travis-ci/travis-ci/issues/8239#issuecomment-373729248

I wonder if we should check if `TRAVIS_BUILD_STAGE_NAME` is set and if it is log a warning or throw an error to tell people they shouldn’t use travis-deploy-once with travis stages?

**Comment by pvdlg** [comment]
What's the value `TRAVIS_BUILD_STAGE_NAME` if there is no build stage configured?

According to the documentation is seems the default Build Stage is `test` which make me think there is always a Build Stage even if none is configured. Basically, I'm not sure if we can rely on `TRAVIS_BUILD_STAGE_NAME` to define is a build stage is configured or not.

**Comment by pvdlg** [comment]
Closing as the project is archived and the library deprecated.
